const PINATA_URL_BASE = "https://api.pinata.cloud";
const PINATA_URL_PINNING_API = `${PINATA_URL_BASE}/pinning`;
const POOLS_FACTORY_ADDRESS = "0x31C1Ed10Feb40FFCC3C4473063a8C5d51b0254fe";

module.exports = {
  PINATA_URL_BASE,
  PINATA_URL_PINNING_API,
  POOLS_FACTORY_ADDRESS,
};
