const PINATA_URL_BASE = "https://api.pinata.cloud";
const PINATA_URL_PINNING_API = `${PINATA_URL_BASE}/pinning`;
const POOLS_FACTORY_ADDRESS = "0x52647D12ADe09627dd23713ED98071A2c89aAc18";

module.exports = {
  PINATA_URL_BASE,
  PINATA_URL_PINNING_API,
  POOLS_FACTORY_ADDRESS,
};
